### ISSUE TITLE
add vuex to vue project

### ISSUE THREAD

**Issue by lisandroiraguen** [nothingalike/lift-wallet#23]
is important to keep the backend and frontend in separated layers, especially if the project grows in size

**Comment by lisandroiraguen** [comment]
https://github.com/vue-electron/vuex-electron-example

**Comment by nothingalike** [comment]
@lisandroiraguen why did you close this issue?

**Comment by lisandroiraguen** [comment]
well, I already added it, but we can re-open it until you review the code >D

**Comment by nothingalike** [comment]
Thank you for setting up vuex
