### ISSUE TITLE
Add validation to Add Wallet form

### ISSUE THREAD

**Issue by lisandroiraguen** [nothingalike/lift-wallet#29]
I do click add
![image](https://user-images.githubusercontent.com/35784914/106366181-e9ee3700-6318-11eb-9529-a664f910d707.png)

then I am trying to add an existing wallet

![image](https://user-images.githubusercontent.com/35784914/106366170-d773fd80-6318-11eb-8322-38a7f1e12041.png)

and I am not able to add a new one.

**Comment by nothingalike** [comment]
> I do click add
> 
> ![image](https://user-images.githubusercontent.com/35784914/106366181-e9ee3700-6318-11eb-9529-a664f910d707.png)
> 
> 
> 
> then I am trying to add an existing wallet
> 
> 
> 
> ![image](https://user-images.githubusercontent.com/35784914/106366170-d773fd80-6318-11eb-8322-38a7f1e12041.png)
> 
> 
> 
> and I am not able to add a new one.
> 
> 
> 
> 

Is your mnemonic only 9 words?

**Comment by lisandroiraguen** [comment]
yes, 9 words

**Comment by nothingalike** [comment]
I believe the min word count is 15. See Wallet Create: https://input-output-hk.github.io/cardano-wallet/api/edge/#operation/postWallet

**Comment by lisandroiraguen** [comment]
then I think we should add some kind of form validation
