### ISSUE TITLE
import error 

### ISSUE THREAD

**Issue by lisandroiraguen** [nothingalike/lift-wallet#32]
when I have a wallet and I am trying to import it
![image](https://user-images.githubusercontent.com/35784914/106521992-cf08f780-64bd-11eb-9dcc-abb0b4fddb3f.png)
it displays an error
![image](https://user-images.githubusercontent.com/35784914/106522084-ef38b680-64bd-11eb-8ef2-70778104215f.png)
and I can't use an existing wallet.
I think it is because once the user creates a wallet, then close the program and re-open it, the wallet is not there anymore, but it exists on the Cardano backend, but I am not sure.

**Comment by nothingalike** [comment]
1. Are you able to create a new wallet?
2. When you restart the wallet you do not see any previous wallets?

Wallets should be created/stored in the following path
`cardano/wallets/testnet/`
Do you see any folders here?

**Comment by lisandroiraguen** [comment]
yes, wallets are there, but the program doesn't set it up.
look
![image](https://user-images.githubusercontent.com/35784914/106948329-5480e780-670a-11eb-9fed-385ec30ae4c6.png)

**Comment by nothingalike** [comment]
The wallet should be the one creating these folders with the wallet files inside. When the wallet loads, it should find these folders and populate these as your wallets on the left side.

![image](https://user-images.githubusercontent.com/638507/106978592-873ad800-672a-11eb-9d47-e96373ad5454.png)

As you can see I have 3 wallets, Perdix 1/2/3

Your wallet should load your four wallets.

**Comment by lisandroiraguen** [comment]
I found the error:
when I have tried to create the first wallet with 9 words with no success, the program has created a mid filled folder, then now it is crashing the wallet loader at that point
![image](https://user-images.githubusercontent.com/35784914/107064197-04f9f480-67ba-11eb-8fc4-78fe9f12b030.png)

we must add a try-catch to prevent the wallet loading process from crashing

**Comment by lisandroiraguen** [comment]
when my wallet creation failed, then it wasn't impossible to load other wallets, now with the try-catch it is working
![image](https://user-images.githubusercontent.com/35784914/107150412-6ea20c00-693c-11eb-83aa-c59c4f1d06e6.png)
if the wallet loading fails, it must continue loading other wallets.
