### ISSUE TITLE
Optimize wallet components

### ISSUE THREAD

**Issue by nothingalike** [nothingalike/lift-wallet#4]
Currently the wallet details is 'doing too much'. I have stubbed out components needed for the `WalletDetail.vue` tabs. This could also improve the transaction polling.

**Comment by lisandroiraguen** [comment]
I can do this part >D

**Comment by lisandroiraguen** [comment]
you can assign this issue to me >D

**Comment by nothingalike** [comment]
Thanks for jumping into the project and helping!

**Comment by lisandroiraguen** [comment]
it was marged to devlop branch
