### ISSUE TITLE
[FR] Bundle specific `cardano-wallet` release binaries on bundle builds

### ISSUE THREAD

**Issue by rcmorano** [nothingalike/lift-wallet#41]
It would be cool to have have binaries for different platforms automatically bundled so releasing process doesn't rely on our ability as human to include correct versions.

**Comment by elribonazo** [comment]
Have added a [pull request](https://github.com/CodingOnChain/lift-wallet/pull/53) for downloading the binaries.

```javascript
npm run binaries:darwin etc
```

**Comment by rcmorano** [comment]
Closed by pr #53
